// =============================================
// LISTA MAESTRA DE ESTAMPAS — MUNDIAL 2026
// =============================================
// Pegá acá el array STICKERS que tenés en tu index.html actual
// Asegurate de agregar flag:"🇦🇷" (emoji de bandera) a cada objeto
// =============================================

const STICKERS = [
    // Introducción / General
    {id:"00",name:"Panini Logo",team:"General",type:"foil"},
    {id:"FWC1",name:"Official Emblem",team:"General",type:"foil"},
    {id:"FWC2",name:"Official Emblem",team:"General",type:"foil"},
    {id:"FWC3",name:"Official Mascots",team:"General",type:"foil"},
    {id:"FWC4",name:"Official Slogan",team:"General",type:"foil"},
    {id:"FWC5",name:"Official Ball",team:"General",type:"foil"},
    {id:"FWC6",name:"Canada - Host Countries & Cities",team:"General",type:"foil"},
    {id:"FWC7",name:"Mexico - Host Countries & Cities",team:"General",type:"foil"},
    {id:"FWC8",name:"USA - Host Countries & Cities",team:"General",type:"foil"},
    {id:"FWC9",name:"ITALY",team:"General",type:"foil"},
    {id:"FWC10",name:"URUGUAY",team:"General",type:"foil"},
    {id:"FWC11",name:"GERMANY",team:"General",type:"foil"},
    {id:"FWC12",name:"BRAZIL",team:"General",type:"foil"},
    {id:"FWC13",name:"GERMANY",team:"General",type:"foil"},
    {id:"FWC14",name:"ARGENTINA",team:"General",type:"foil"},
    {id:"FWC15",name:"BRAZIL",team:"General",type:"foil"},
    {id:"FWC16",name:"BRAZIL",team:"General",type:"foil"},
    {id:"FWC17",name:"ITALY",team:"General",type:"foil"},
    {id:"FWC18",name:"GERMANY",team:"General",type:"foil"},
    {id:"FWC19",name:"ARGENTINA",team:"General",type:"foil"},

    // Mexico
    {id:"MEX1",name:"Team Logo",team:"México",type:"foil"},
    {id:"MEX2",name:"Luis Malagón",team:"México"},
    {id:"MEX3",name:"Johan Vásquez",team:"México"},
    {id:"MEX4",name:"Jorge Sánchez",team:"México"},
    {id:"MEX5",name:"Cesar Montes",team:"México"},
    {id:"MEX6",name:"Jesus Gallardo",team:"México"},
    {id:"MEX7",name:"Israel Reyes",team:"México"},
    {id:"MEX8",name:"Diego Lainez",team:"México"},
    {id:"MEX9",name:"Carlos Rodriguez",team:"México"},
    {id:"MEX10",name:"Edson Alvarez",team:"México"},
    {id:"MEX11",name:"Orbelin Pineda",team:"México"},
    {id:"MEX12",name:"Marcel Ruiz",team:"México"},
    {id:"MEX13",name:"Team Photo",team:"México"},
    {id:"MEX14",name:"Érick Sánchez",team:"México"},
    {id:"MEX15",name:"Hirving Lozano",team:"México"},
    {id:"MEX16",name:"Santiago Giménez",team:"México"},
    {id:"MEX17",name:"Raúl Jiménez",team:"México"},
    {id:"MEX18",name:"Alexis Vega",team:"México"},
    {id:"MEX19",name:"Roberto Alvarado",team:"México"},
    {id:"MEX20",name:"Cesar Huerta",team:"México"},
    // South Africa
    {id:"RSA1",name:"Team Logo",team:"Sudáfrica",type:"foil"},
    {id:"RSA2",name:"Ronwen Williams",team:"Sudáfrica"},
    {id:"RSA3",name:"Sipho Chaine",team:"Sudáfrica"},
    {id:"RSA4",name:"Aubrey Modiba",team:"Sudáfrica"},
    {id:"RSA5",name:"Samukele Kabini",team:"Sudáfrica"},
    {id:"RSA6",name:"Mbekezeli Mbokazi",team:"Sudáfrica"},
    {id:"RSA7",name:"Khulumani Ndamane",team:"Sudáfrica"},
    {id:"RSA8",name:"Siyabonga Ngezana",team:"Sudáfrica"},
    {id:"RSA9",name:"Khuliso Mudau",team:"Sudáfrica"},
    {id:"RSA10",name:"Nkosinathi Sibisi",team:"Sudáfrica"},
    {id:"RSA11",name:"Teboho Mokoena",team:"Sudáfrica"},
    {id:"RSA12",name:"Thalente Mbatha",team:"Sudáfrica"},
    {id:"RSA13",name:"Team Photo",team:"Sudáfrica"},
    {id:"RSA14",name:"Bathasi Aubaas",team:"Sudáfrica"},
    {id:"RSA15",name:"Yaya Sithole",team:"Sudáfrica"},
    {id:"RSA16",name:"Sipho Mbule",team:"Sudáfrica"},
    {id:"RSA17",name:"Lyle Foster",team:"Sudáfrica"},
    {id:"RSA18",name:"Iqraam Rayners",team:"Sudáfrica"},
    {id:"RSA19",name:"Mohau Nkota",team:"Sudáfrica"},
    {id:"RSA20",name:"Oswin Appollis",team:"Sudáfrica"},
    // South Korea
    {id:"KOR1",name:"Team Logo",team:"Corea del Sur",type:"foil"},
    {id:"KOR2",name:"Hyeon-woo Jo",team:"Corea del Sur"},
    {id:"KOR3",name:"Seung-Gyu Kim",team:"Corea del Sur"},
    {id:"KOR4",name:"Min-jae Kim",team:"Corea del Sur"},
    {id:"KOR5",name:"Yu-min Cho",team:"Corea del Sur"},
    {id:"KOR6",name:"Young-woo Seol",team:"Corea del Sur"},
    {id:"KOR7",name:"Han-beom Lee",team:"Corea del Sur"},
    {id:"KOR8",name:"Tae-seok Lee",team:"Corea del Sur"},
    {id:"KOR9",name:"Myung-jae Lee",team:"Corea del Sur"},
    {id:"KOR10",name:"Jae-sung Lee",team:"Corea del Sur"},
    {id:"KOR11",name:"In-beom Hwang",team:"Corea del Sur"},
    {id:"KOR12",name:"Kang-in Lee",team:"Corea del Sur"},
    {id:"KOR13",name:"Team Photo",team:"Corea del Sur"},
    {id:"KOR14",name:"Seung-ho Paik",team:"Corea del Sur"},
    {id:"KOR15",name:"Jens Castrop",team:"Corea del Sur"},
    {id:"KOR16",name:"Dongg-yeong Lee",team:"Corea del Sur"},
    {id:"KOR17",name:"Gue-sung Cho",team:"Corea del Sur"},
    {id:"KOR18",name:"Heung-min Son",team:"Corea del Sur"},
    {id:"KOR19",name:"Hee-chan Hwang",team:"Corea del Sur"},
    {id:"KOR20",name:"Hyeon-Gyu Oh",team:"Corea del Sur"},
    // Czechia
    {id:"CZE1",name:"Team Logo",team:"Chequia",type:"foil"},
    {id:"CZE2",name:"Matej Kovar",team:"Chequia"},
    {id:"CZE3",name:"Jindrich Stanek",team:"Chequia"},
    {id:"CZE4",name:"Ladislav Krejci",team:"Chequia"},
    {id:"CZE5",name:"Vladimir Coufal",team:"Chequia"},
    {id:"CZE6",name:"Jaroslav Zeleny",team:"Chequia"},
    {id:"CZE7",name:"Tomas Holes",team:"Chequia"},
    {id:"CZE8",name:"David Zima",team:"Chequia"},
    {id:"CZE9",name:"Michal Sadilek",team:"Chequia"},
    {id:"CZE10",name:"Lukas Provod",team:"Chequia"},
    {id:"CZE11",name:"Lukas Cerv",team:"Chequia"},
    {id:"CZE12",name:"Tomas Soucek",team:"Chequia"},
    {id:"CZE13",name:"Team Photo",team:"Chequia"},
    {id:"CZE14",name:"Pavel Sulc",team:"Chequia"},
    {id:"CZE15",name:"Matej Vydra",team:"Chequia"},
    {id:"CZE16",name:"Vasil Kusej",team:"Chequia"},
    {id:"CZE17",name:"Tomas Chory",team:"Chequia"},
    {id:"CZE18",name:"Vaclav Cerny",team:"Chequia"},
    {id:"CZE19",name:"Adam Hlozek",team:"Chequia"},
    {id:"CZE20",name:"Patrik Schick",team:"Chequia"},
    // Canada
    {id:"CAN1",name:"Team Logo",team:"Canadá",type:"foil"},
    {id:"CAN2",name:"Dayne St.Clair",team:"Canadá"},
    {id:"CAN3",name:"Alphonso Davies",team:"Canadá"},
    {id:"CAN4",name:"Alistair Johnston",team:"Canadá"},
    {id:"CAN5",name:"Samuel Adekugbe",team:"Canadá"},
    {id:"CAN6",name:"Riche Larvea",team:"Canadá"},
    {id:"CAN7",name:"Derek Cornelius",team:"Canadá"},
    {id:"CAN8",name:"Moïse Bombito",team:"Canadá"},
    {id:"CAN9",name:"Kamal Miller",team:"Canadá"},
    {id:"CAN10",name:"Stephen Eustáquio",team:"Canadá"},
    {id:"CAN11",name:"Ismaël Koné",team:"Canadá"},
    {id:"CAN12",name:"Jonathan Osorio",team:"Canadá"},
    {id:"CAN13",name:"Team Photo",team:"Canadá"},
    {id:"CAN14",name:"Jacob Shaffelburg",team:"Canadá"},
    {id:"CAN15",name:"Mathieu Choinière",team:"Canadá"},
    {id:"CAN16",name:"Niko Sigur",team:"Canadá"},
    {id:"CAN17",name:"Tajon Buchanan",team:"Canadá"},
    {id:"CAN18",name:"Liam Millar",team:"Canadá"},
    {id:"CAN19",name:"Cyle Larin",team:"Canadá"},
    {id:"CAN20",name:"Jonathan David",team:"Canadá"},
    // Bosnia
    {id:"BIH1",name:"Team Logo",team:"Bosnia",type:"foil"},
    {id:"BIH2",name:"Nikola Vasilj",team:"Bosnia"},
    {id:"BIH3",name:"Amer Dedic",team:"Bosnia"},
    {id:"BIH4",name:"Sead Kolasinac",team:"Bosnia"},
    {id:"BIH5",name:"Tarik Muharemovic",team:"Bosnia"},
    {id:"BIH6",name:"Nihad Mujakic",team:"Bosnia"},
    {id:"BIH7",name:"Nikola Katic",team:"Bosnia"},
    {id:"BIH8",name:"Amir Hadziahmetovic",team:"Bosnia"},
    {id:"BIH9",name:"Benjamin Tahirovic",team:"Bosnia"},
    {id:"BIH10",name:"Armin Gigovic",team:"Bosnia"},
    {id:"BIH11",name:"Ivan Sunjic",team:"Bosnia"},
    {id:"BIH12",name:"Ivan Basic",team:"Bosnia"},
    {id:"BIH13",name:"Team Photo",team:"Bosnia"},
    {id:"BIH14",name:"Dzenis Burnic",team:"Bosnia"},
    {id:"BIH15",name:"Esmir Bajraktarevic",team:"Bosnia"},
    {id:"BIH16",name:"Amar Memic",team:"Bosnia"},
    {id:"BIH17",name:"Ermedin Demirovic",team:"Bosnia"},
    {id:"BIH18",name:"Edin Dzeko",team:"Bosnia"},
    {id:"BIH19",name:"Samed Bazdar",team:"Bosnia"},
    {id:"BIH20",name:"Haris Tabakovic",team:"Bosnia"},
    // Qatar
    {id:"QAT1",name:"Team Logo",team:"Qatar",type:"foil"},
    {id:"QAT2",name:"Meshaal Barsham",team:"Qatar"},
    {id:"QAT3",name:"Sultan Albrake",team:"Qatar"},
    {id:"QAT4",name:"Lucas Mendes",team:"Qatar"},
    {id:"QAT5",name:"Homam Ahmed",team:"Qatar"},
    {id:"QAT6",name:"Boualem Khoukhi",team:"Qatar"},
    {id:"QAT7",name:"Pedro Miguel",team:"Qatar"},
    {id:"QAT8",name:"Tarek Salman",team:"Qatar"},
    {id:"QAT9",name:"Mohamed Al-Mannai",team:"Qatar"},
    {id:"QAT10",name:"Karim Boudiaf",team:"Qatar"},
    {id:"QAT11",name:"Assim Madibo",team:"Qatar"},
    {id:"QAT12",name:"Ahmed Fatehi",team:"Qatar"},
    {id:"QAT13",name:"Team Photo",team:"Qatar"},
    {id:"QAT14",name:"Mohammed Waad",team:"Qatar"},
    {id:"QAT15",name:"Abdulaziz Hatem",team:"Qatar"},
    {id:"QAT16",name:"Hassan Al-Haydos",team:"Qatar"},
    {id:"QAT17",name:"Edmilson Junior",team:"Qatar"},
    {id:"QAT18",name:"Akram Hassan Afif",team:"Qatar"},
    {id:"QAT19",name:"Ahmed Al Ganehi",team:"Qatar"},
    {id:"QAT20",name:"Almoez Ali",team:"Qatar"},
    // Switzerland
    {id:"SUI1",name:"Team Logo",team:"Suiza",type:"foil"},
    {id:"SUI2",name:"Gregor Kobel",team:"Suiza"},
    {id:"SUI3",name:"Yvon Mvogo",team:"Suiza"},
    {id:"SUI4",name:"Manuel Akanji",team:"Suiza"},
    {id:"SUI5",name:"Ricardo Rodriguez",team:"Suiza"},
    {id:"SUI6",name:"Nico Elvedi",team:"Suiza"},
    {id:"SUI7",name:"Aurèle Amenda",team:"Suiza"},
    {id:"SUI8",name:"Silvan Widmer",team:"Suiza"},
    {id:"SUI9",name:"Granit Xhaka",team:"Suiza"},
    {id:"SUI10",name:"Denis Zakaria",team:"Suiza"},
    {id:"SUI11",name:"Remo Freuler",team:"Suiza"},
    {id:"SUI12",name:"Fabian Rieder",team:"Suiza"},
    {id:"SUI13",name:"Team Photo",team:"Suiza"},
    {id:"SUI14",name:"Ardon Jashari",team:"Suiza"},
    {id:"SUI15",name:"Johan Manzambi",team:"Suiza"},
    {id:"SUI16",name:"Michel Aebischer",team:"Suiza"},
    {id:"SUI17",name:"Breel Embolo",team:"Suiza"},
    {id:"SUI18",name:"Ruben Vargas",team:"Suiza"},
    {id:"SUI19",name:"Dan Ndoye",team:"Suiza"},
    {id:"SUI20",name:"Zeki Amdouni",team:"Suiza"},
    // Brazil
    {id:"BRA1",name:"Team Logo",team:"Brasil",type:"foil"},
    {id:"BRA2",name:"Alisson",team:"Brasil"},
    {id:"BRA3",name:"Bento",team:"Brasil"},
    {id:"BRA4",name:"Marquinhos",team:"Brasil"},
    {id:"BRA5",name:"Éder Militão",team:"Brasil"},
    {id:"BRA6",name:"Gabriel Magalhães",team:"Brasil"},
    {id:"BRA7",name:"Danilo",team:"Brasil"},
    {id:"BRA8",name:"Wesley",team:"Brasil"},
    {id:"BRA9",name:"Lucas Paquetá",team:"Brasil"},
    {id:"BRA10",name:"Casemiro",team:"Brasil"},
    {id:"BRA11",name:"Bruno Guimarães",team:"Brasil"},
    {id:"BRA12",name:"Luiz Henrique",team:"Brasil"},
    {id:"BRA13",name:"Team Photo",team:"Brasil"},
    {id:"BRA14",name:"Vinicius Júnior",team:"Brasil"},
    {id:"BRA15",name:"Rodrygo",team:"Brasil"},
    {id:"BRA16",name:"João Pedro",team:"Brasil"},
    {id:"BRA17",name:"Matheus Cunha",team:"Brasil"},
    {id:"BRA18",name:"Gabriel Martinelli",team:"Brasil"},
    {id:"BRA19",name:"Raphinha",team:"Brasil"},
    {id:"BRA20",name:"Estévão",team:"Brasil"},
    // Morocco
    {id:"MAR1",name:"Team Logo",team:"Marruecos",type:"foil"},
    {id:"MAR2",name:"Yassine Bounou",team:"Marruecos"},
    {id:"MAR3",name:"Munir El Kajoui",team:"Marruecos"},
    {id:"MAR4",name:"Achraf Hakimi",team:"Marruecos"},
    {id:"MAR5",name:"Noussair Mazraoui",team:"Marruecos"},
    {id:"MAR6",name:"Nayef Aguerd",team:"Marruecos"},
    {id:"MAR7",name:"Roman Saiss",team:"Marruecos"},
    {id:"MAR8",name:"Jawad El Yamio",team:"Marruecos"},
    {id:"MAR9",name:"Adam Masina",team:"Marruecos"},
    {id:"MAR10",name:"Sofyan Amrabat",team:"Marruecos"},
    {id:"MAR11",name:"Azzedine Ounahi",team:"Marruecos"},
    {id:"MAR12",name:"Eliesse Ben Seghir",team:"Marruecos"},
    {id:"MAR13",name:"Team Photo",team:"Marruecos"},
    {id:"MAR14",name:"Bilal El Khannouss",team:"Marruecos"},
    {id:"MAR15",name:"Ismael Saibari",team:"Marruecos"},
    {id:"MAR16",name:"Youssef En-Nesyri",team:"Marruecos"},
    {id:"MAR17",name:"Abde Ezzalzouli",team:"Marruecos"},
    {id:"MAR18",name:"Soufiane Rahimi",team:"Marruecos"},
    {id:"MAR19",name:"Brahim Diaz",team:"Marruecos"},
    {id:"MAR20",name:"Ayoub El Kaabi",team:"Marruecos"},
    // Haiti
    {id:"HAI1",name:"Team Logo",team:"Haití",type:"foil"},
    {id:"HAI2",name:"Johny Placide",team:"Haití"},
    {id:"HAI3",name:"Carlens Arcus",team:"Haití"},
    {id:"HAI4",name:"Martin Expérience",team:"Haití"},
    {id:"HAI5",name:"Jean-Kevin Duverne",team:"Haití"},
    {id:"HAI6",name:"Ricardo Adé",team:"Haití"},
    {id:"HAI7",name:"Duke Lacroix",team:"Haití"},
    {id:"HAI8",name:"Garven Metusala",team:"Haití"},
    {id:"HAI9",name:"Hannes Delcroix",team:"Haití"},
    {id:"HAI10",name:"Leverton Pierre",team:"Haití"},
    {id:"HAI11",name:"Danley Jean Jacques",team:"Haití"},
    {id:"HAI12",name:"Jean-Ricner Bellegarde",team:"Haití"},
    {id:"HAI13",name:"Team Photo",team:"Haití"},
    {id:"HAI14",name:"Christopher Attys",team:"Haití"},
    {id:"HAI15",name:"Derrick Etienne Jr",team:"Haití"},
    {id:"HAI16",name:"Josue Casimir",team:"Haití"},
    {id:"HAI17",name:"Ruben Providence",team:"Haití"},
    {id:"HAI18",name:"Duckens Nazon",team:"Haití"},
    {id:"HAI19",name:"Louicius Deedson",team:"Haití"},
    {id:"HAI20",name:"Frantzdy Pierrot",team:"Haití"},
    // Scotland
    {id:"SCO1",name:"Team Logo",team:"Escocia",type:"foil"},
    {id:"SCO2",name:"Angus Gunn",team:"Escocia"},
    {id:"SCO3",name:"Jack Hendry",team:"Escocia"},
    {id:"SCO4",name:"Kieran Tierney",team:"Escocia"},
    {id:"SCO5",name:"Aaron Hickey",team:"Escocia"},
    {id:"SCO6",name:"Andrew Robertson",team:"Escocia"},
    {id:"SCO7",name:"Scott McKenna",team:"Escocia"},
    {id:"SCO8",name:"John Souttar",team:"Escocia"},
    {id:"SCO9",name:"Anthony Ralston",team:"Escocia"},
    {id:"SCO10",name:"Grant Hanley",team:"Escocia"},
    {id:"SCO11",name:"Scott McTominay",team:"Escocia"},
    {id:"SCO12",name:"Billy Gilmour",team:"Escocia"},
    {id:"SCO13",name:"Team Photo",team:"Escocia"},
    {id:"SCO14",name:"Lewis Ferguson",team:"Escocia"},
    {id:"SCO15",name:"Ryan Christie",team:"Escocia"},
    {id:"SCO16",name:"Kenny McLean",team:"Escocia"},
    {id:"SCO17",name:"John McGinn",team:"Escocia"},
    {id:"SCO18",name:"Lyndon Dykes",team:"Escocia"},
    {id:"SCO19",name:"Che Adams",team:"Escocia"},
    {id:"SCO20",name:"Ben Gannon-Doak",team:"Escocia"},
    // USA
    {id:"USA1",name:"Team Logo",team:"USA",type:"foil"},
    {id:"USA2",name:"Matt Freese",team:"USA"},
    {id:"USA3",name:"Chris Richards",team:"USA"},
    {id:"USA4",name:"Tim Ream",team:"USA"},
    {id:"USA5",name:"Mark McKenzie",team:"USA"},
    {id:"USA6",name:"Alex Freeman",team:"USA"},
    {id:"USA7",name:"Antonee Robinson",team:"USA"},
    {id:"USA8",name:"Tyler Adams",team:"USA"},
    {id:"USA9",name:"Tanner Tessmann",team:"USA"},
    {id:"USA10",name:"Weston McKennie",team:"USA"},
    {id:"USA11",name:"Christian Roldan",team:"USA"},
    {id:"USA12",name:"Timothy Weah",team:"USA"},
    {id:"USA13",name:"Team Photo",team:"USA"},
    {id:"USA14",name:"Diego Luna",team:"USA"},
    {id:"USA15",name:"Malik Tillman",team:"USA"},
    {id:"USA16",name:"Christian Pulisic",team:"USA"},
    {id:"USA17",name:"Brenden Aaronson",team:"USA"},
    {id:"USA18",name:"Ricardo Pepi",team:"USA"},
    {id:"USA19",name:"Haji Wright",team:"USA"},
    {id:"USA20",name:"Folarin Balogun",team:"USA"},
    // Paraguay
    {id:"PAR1",name:"Team Logo",team:"Paraguay",type:"foil"},
    {id:"PAR2",name:"Roberto Fernandez",team:"Paraguay"},
    {id:"PAR3",name:"Orlando Gill",team:"Paraguay"},
    {id:"PAR4",name:"Gustavo Gomez",team:"Paraguay"},
    {id:"PAR5",name:"Fabián Balbuena",team:"Paraguay"},
    {id:"PAR6",name:"Juan José Cáceres",team:"Paraguay"},
    {id:"PAR7",name:"Omar Alderete",team:"Paraguay"},
    {id:"PAR8",name:"Junior Alonso",team:"Paraguay"},
    {id:"PAR9",name:"Mathías Villasanti",team:"Paraguay"},
    {id:"PAR10",name:"Diego Gomez",team:"Paraguay"},
    {id:"PAR11",name:"Damián Bobadilla",team:"Paraguay"},
    {id:"PAR12",name:"Andres Cubas",team:"Paraguay"},
    {id:"PAR13",name:"Team Photo",team:"Paraguay"},
    {id:"PAR14",name:"Matias Galarza Fonda",team:"Paraguay"},
    {id:"PAR15",name:"Julio Enciso",team:"Paraguay"},
    {id:"PAR16",name:"Alejandro Romero Gamarra",team:"Paraguay"},
    {id:"PAR17",name:"Miguel Almirón",team:"Paraguay"},
    {id:"PAR18",name:"Ramon Sosa",team:"Paraguay"},
    {id:"PAR19",name:"Angel Romero",team:"Paraguay"},
    {id:"PAR20",name:"Antonio Sanabria",team:"Paraguay"},
    // Australia
    {id:"AUS1",name:"Team Logo",team:"Australia",type:"foil"},
    {id:"AUS2",name:"Mathew Ryan",team:"Australia"},
    {id:"AUS3",name:"Joe Gauci",team:"Australia"},
    {id:"AUS4",name:"Harry Souttar",team:"Australia"},
    {id:"AUS5",name:"Alessandro Circati",team:"Australia"},
    {id:"AUS6",name:"Jordan Bos",team:"Australia"},
    {id:"AUS7",name:"Aziz Behich",team:"Australia"},
    {id:"AUS8",name:"Cameron Burgess",team:"Australia"},
    {id:"AUS9",name:"Lewis Miller",team:"Australia"},
    {id:"AUS10",name:"Milos Degenek",team:"Australia"},
    {id:"AUS11",name:"Jackson Irvine",team:"Australia"},
    {id:"AUS12",name:"Riley McGree",team:"Australia"},
    {id:"AUS13",name:"Team Photo",team:"Australia"},
    {id:"AUS14",name:"Aiden O'Neill",team:"Australia"},
    {id:"AUS15",name:"Connor Metcalfe",team:"Australia"},
    {id:"AUS16",name:"Patrick Yazbek",team:"Australia"},
    {id:"AUS17",name:"Craig Goodwin",team:"Australia"},
    {id:"AUS18",name:"Kusini Vengi",team:"Australia"},
    {id:"AUS19",name:"Nestory Irankunda",team:"Australia"},
    {id:"AUS20",name:"Mohamed Touré",team:"Australia"},
    // Türkiye
    {id:"TUR1",name:"Team Logo",team:"Turquía",type:"foil"},
    {id:"TUR2",name:"Ugurcan Cakir",team:"Turquía"},
    {id:"TUR3",name:"Mert Muldur",team:"Turquía"},
    {id:"TUR4",name:"Zeki Celik",team:"Turquía"},
    {id:"TUR5",name:"Abdulkerim Bardakci",team:"Turquía"},
    {id:"TUR6",name:"Caglar Soyuncu",team:"Turquía"},
    {id:"TUR7",name:"Merih Demiral",team:"Turquía"},
    {id:"TUR8",name:"Ferdi Kadioglu",team:"Turquía"},
    {id:"TUR9",name:"Kaan Ayhan",team:"Turquía"},
    {id:"TUR10",name:"Ismail Yuksek",team:"Turquía"},
    {id:"TUR11",name:"Hakan Calhanoglu",team:"Turquía"},
    {id:"TUR12",name:"Orkun Kokcu",team:"Turquía"},
    {id:"TUR13",name:"Team Photo",team:"Turquía"},
    {id:"TUR14",name:"Arda Guler",team:"Turquía"},
    {id:"TUR15",name:"Irfan Can Kahveci",team:"Turquía"},
    {id:"TUR16",name:"Yunus Akgun",team:"Turquía"},
    {id:"TUR17",name:"Can Uzun",team:"Turquía"},
    {id:"TUR18",name:"Baris Alper Yilmaz",team:"Turquía"},
    {id:"TUR19",name:"Kerem Akturkoglu",team:"Turquía"},
    {id:"TUR20",name:"Kenan Yildiz",team:"Turquía"},
    // Germany
    {id:"GER1",name:"Team Logo",team:"Alemania",type:"foil"},
    {id:"GER2",name:"Marc-André ter Stegen",team:"Alemania"},
    {id:"GER3",name:"Jonathan Tah",team:"Alemania"},
    {id:"GER4",name:"David Raum",team:"Alemania"},
    {id:"GER5",name:"Nico Schlotterbeck",team:"Alemania"},
    {id:"GER6",name:"Antonio Rüdiger",team:"Alemania"},
    {id:"GER7",name:"Waldemar Anton",team:"Alemania"},
    {id:"GER8",name:"Ridle Baku",team:"Alemania"},
    {id:"GER9",name:"Maximilian Mittelstadt",team:"Alemania"},
    {id:"GER10",name:"Joshua Kimmich",team:"Alemania"},
    {id:"GER11",name:"Florian Wirtz",team:"Alemania"},
    {id:"GER12",name:"Felix Nmecha",team:"Alemania"},
    {id:"GER13",name:"Team Photo",team:"Alemania"},
    {id:"GER14",name:"Leon Goretzka",team:"Alemania"},
    {id:"GER15",name:"Jamal Musiala",team:"Alemania"},
    {id:"GER16",name:"Serge Gnabry",team:"Alemania"},
    {id:"GER17",name:"Kai Havertz",team:"Alemania"},
    {id:"GER18",name:"Leroy Sane",team:"Alemania"},
    {id:"GER19",name:"Karim Adeyemi",team:"Alemania"},
    {id:"GER20",name:"Nick Woltemade",team:"Alemania"},
    // Curaçao
    {id:"CUW1",name:"Team Logo",team:"Curaçao",type:"foil"},
    {id:"CUW2",name:"Eloy Room",team:"Curaçao"},
    {id:"CUW3",name:"Armando Obispo",team:"Curaçao"},
    {id:"CUW4",name:"Sherel Floranus",team:"Curaçao"},
    {id:"CUW5",name:"Jurien Gaari",team:"Curaçao"},
    {id:"CUW6",name:"Joshua Brenet",team:"Curaçao"},
    {id:"CUW7",name:"Roshon Van Eijma",team:"Curaçao"},
    {id:"CUW8",name:"Shurandy Sambo",team:"Curaçao"},
    {id:"CUW9",name:"Livano Comenencia",team:"Curaçao"},
    {id:"CUW10",name:"Godfried Roemeratoe",team:"Curaçao"},
    {id:"CUW11",name:"Juninho Bacuna",team:"Curaçao"},
    {id:"CUW12",name:"Leandro Bacuna",team:"Curaçao"},
    {id:"CUW13",name:"Team Photo",team:"Curaçao"},
    {id:"CUW14",name:"Tahith Chong",team:"Curaçao"},
    {id:"CUW15",name:"Kenji Gorre",team:"Curaçao"},
    {id:"CUW16",name:"Jearl Margaritha",team:"Curaçao"},
    {id:"CUW17",name:"Jurgen Locadia",team:"Curaçao"},
    {id:"CUW18",name:"Jeremy Antonisse",team:"Curaçao"},
    {id:"CUW19",name:"Gervane Kastaneer",team:"Curaçao"},
    {id:"CUW20",name:"Sontje Hansen",team:"Curaçao"},
    // Ivory Coast
    {id:"CIV1",name:"Team Logo",team:"Costa de Marfil",type:"foil"},
    {id:"CIV2",name:"Yahia Fofana",team:"Costa de Marfil"},
    {id:"CIV3",name:"Ghislain Konan",team:"Costa de Marfil"},
    {id:"CIV4",name:"Wilfried Singo",team:"Costa de Marfil"},
    {id:"CIV5",name:"Odilon Kossounou",team:"Costa de Marfil"},
    {id:"CIV6",name:"Evan Ndicka",team:"Costa de Marfil"},
    {id:"CIV7",name:"Willy Boly",team:"Costa de Marfil"},
    {id:"CIV8",name:"Emmanuel Agbadou",team:"Costa de Marfil"},
    {id:"CIV9",name:"Ousmane Diomande",team:"Costa de Marfil"},
    {id:"CIV10",name:"Franck Kessie",team:"Costa de Marfil"},
    {id:"CIV11",name:"Seko Fofana",team:"Costa de Marfil"},
    {id:"CIV12",name:"Ibrahim Sangare",team:"Costa de Marfil"},
    {id:"CIV13",name:"Team Photo",team:"Costa de Marfil"},
    {id:"CIV14",name:"Jean-Philippe Gbamin",team:"Costa de Marfil"},
    {id:"CIV15",name:"Amad Diallo",team:"Costa de Marfil"},
    {id:"CIV16",name:"Sébastien Haller",team:"Costa de Marfil"},
    {id:"CIV17",name:"Simon Adingra",team:"Costa de Marfil"},
    {id:"CIV18",name:"Yan Diomande",team:"Costa de Marfil"},
    {id:"CIV19",name:"Evann Guessand",team:"Costa de Marfil"},
    {id:"CIV20",name:"Oumar Diakite",team:"Costa de Marfil"},
    // Ecuador
    {id:"ECU1",name:"Team Logo",team:"Ecuador",type:"foil"},
    {id:"ECU2",name:"Hernán Galíndez",team:"Ecuador"},
    {id:"ECU3",name:"Gonzalo Valle",team:"Ecuador"},
    {id:"ECU4",name:"Piero Hincapié",team:"Ecuador"},
    {id:"ECU5",name:"Pervis Estupiñán",team:"Ecuador"},
    {id:"ECU6",name:"Willian Pacho",team:"Ecuador"},
    {id:"ECU7",name:"Ángelo Preciado",team:"Ecuador"},
    {id:"ECU8",name:"Joel Ordóñez",team:"Ecuador"},
    {id:"ECU9",name:"Moises Caicedo",team:"Ecuador"},
    {id:"ECU10",name:"Alan Franco",team:"Ecuador"},
    {id:"ECU11",name:"Kendry Paez",team:"Ecuador"},
    {id:"ECU12",name:"Pedro Vite",team:"Ecuador"},
    {id:"ECU13",name:"Team Photo",team:"Ecuador"},
    {id:"ECU14",name:"John Yeboah",team:"Ecuador"},
    {id:"ECU15",name:"Leonardo Campana",team:"Ecuador"},
    {id:"ECU16",name:"Gonzalo Plata",team:"Ecuador"},
    {id:"ECU17",name:"Nilson Angulo",team:"Ecuador"},
    {id:"ECU18",name:"Alan Minda",team:"Ecuador"},
    {id:"ECU19",name:"Kevin Rodriguez",team:"Ecuador"},
    {id:"ECU20",name:"Enner Valencia",team:"Ecuador"},
    // Netherlands
    {id:"NED1",name:"Team Logo",team:"Países Bajos",type:"foil"},
    {id:"NED2",name:"Bart Verbruggen",team:"Países Bajos"},
    {id:"NED3",name:"Virgil van Dijk",team:"Países Bajos"},
    {id:"NED4",name:"Micky van de Ven",team:"Países Bajos"},
    {id:"NED5",name:"Jurrien Timber",team:"Países Bajos"},
    {id:"NED6",name:"Denzel Dumfries",team:"Países Bajos"},
    {id:"NED7",name:"Nathan Aké",team:"Países Bajos"},
    {id:"NED8",name:"Jeremie Frimpong",team:"Países Bajos"},
    {id:"NED9",name:"Jan Paul van Hecke",team:"Países Bajos"},
    {id:"NED10",name:"Tijjani Reijnders",team:"Países Bajos"},
    {id:"NED11",name:"Ryan Gravenberch",team:"Países Bajos"},
    {id:"NED12",name:"Teun Koopmeiners",team:"Países Bajos"},
    {id:"NED13",name:"Team Photo",team:"Países Bajos"},
    {id:"NED14",name:"Frenkie de Jong",team:"Países Bajos"},
    {id:"NED15",name:"Xavi Simons",team:"Países Bajos"},
    {id:"NED16",name:"Justin Kluivert",team:"Países Bajos"},
    {id:"NED17",name:"Memphis Depay",team:"Países Bajos"},
    {id:"NED18",name:"Donyell Malen",team:"Países Bajos"},
    {id:"NED19",name:"Wout Weghorst",team:"Países Bajos"},
    {id:"NED20",name:"Cody Gakpo",team:"Países Bajos"},
    // Japan
    {id:"JPN1",name:"Team Logo",team:"Japón",type:"foil"},
    {id:"JPN2",name:"Zion Suzuki",team:"Japón"},
    {id:"JPN3",name:"Henry Heroki Mochizuki",team:"Japón"},
    {id:"JPN4",name:"Ayumu Seko",team:"Japón"},
    {id:"JPN5",name:"Junnosuke Suzuki",team:"Japón"},
    {id:"JPN6",name:"Shogo Taniguchi",team:"Japón"},
    {id:"JPN7",name:"Tsuyoshi Watanabe",team:"Japón"},
    {id:"JPN8",name:"Kaishu Sano",team:"Japón"},
    {id:"JPN9",name:"Yuki Soma",team:"Japón"},
    {id:"JPN10",name:"Ao Tanaka",team:"Japón"},
    {id:"JPN11",name:"Daichi Kamada",team:"Japón"},
    {id:"JPN12",name:"Takefusa Kubo",team:"Japón"},
    {id:"JPN13",name:"Team Photo",team:"Japón"},
    {id:"JPN14",name:"Ritsu Doan",team:"Japón"},
    {id:"JPN15",name:"Keito Nakamura",team:"Japón"},
    {id:"JPN16",name:"Takumi Minamino",team:"Japón"},
    {id:"JPN17",name:"Shuto Machino",team:"Japón"},
    {id:"JPN18",name:"Junya Ito",team:"Japón"},
    {id:"JPN19",name:"Koki Ogawa",team:"Japón"},
    {id:"JPN20",name:"Ayase Ueda",team:"Japón"},
    // Sweden
    {id:"SWE1",name:"Team Logo",team:"Suecia",type:"foil"},
    {id:"SWE2",name:"Victor Johansson",team:"Suecia"},
    {id:"SWE3",name:"Isak Hien",team:"Suecia"},
    {id:"SWE4",name:"Gabriel Gudmundsson",team:"Suecia"},
    {id:"SWE5",name:"Emil Holm",team:"Suecia"},
    {id:"SWE6",name:"Victor Nilsson Lindelöf",team:"Suecia"},
    {id:"SWE7",name:"Gustaf Lagerbielke",team:"Suecia"},
    {id:"SWE8",name:"Lucas Bergvall",team:"Suecia"},
    {id:"SWE9",name:"Hugo Larsson",team:"Suecia"},
    {id:"SWE10",name:"Jesper Karlström",team:"Suecia"},
    {id:"SWE11",name:"Yasin Ayari",team:"Suecia"},
    {id:"SWE12",name:"Mattias Svanberg",team:"Suecia"},
    {id:"SWE13",name:"Team Photo",team:"Suecia"},
    {id:"SWE14",name:"Daniel Svensson",team:"Suecia"},
    {id:"SWE15",name:"Ken Sema",team:"Suecia"},
    {id:"SWE16",name:"Roony Bardghji",team:"Suecia"},
    {id:"SWE17",name:"Dejan Kulusevski",team:"Suecia"},
    {id:"SWE18",name:"Anthony Elanga",team:"Suecia"},
    {id:"SWE19",name:"Alexander Isak",team:"Suecia"},
    {id:"SWE20",name:"Viktor Gyökeres",team:"Suecia"},
    // Tunisia
    {id:"TUN1",name:"Team Logo",team:"Túnez",type:"foil"},
    {id:"TUN2",name:"Bechir Ben Said",team:"Túnez"},
    {id:"TUN3",name:"Aymen Dahmen",team:"Túnez"},
    {id:"TUN4",name:"Yan Valery",team:"Túnez"},
    {id:"TUN5",name:"Montassar Talbi",team:"Túnez"},
    {id:"TUN6",name:"Yassine Meriah",team:"Túnez"},
    {id:"TUN7",name:"Ali Abdi",team:"Túnez"},
    {id:"TUN8",name:"Dylan Bronn",team:"Túnez"},
    {id:"TUN9",name:"Ellyes Skhiri",team:"Túnez"},
    {id:"TUN10",name:"Aissa Laidouni",team:"Túnez"},
    {id:"TUN11",name:"Ferjani Sassi",team:"Túnez"},
    {id:"TUN12",name:"Mohamed Ali Ben Romdhane",team:"Túnez"},
    {id:"TUN13",name:"Team Photo",team:"Túnez"},
    {id:"TUN14",name:"Hannibal Mejbri",team:"Túnez"},
    {id:"TUN15",name:"Elias Achouri",team:"Túnez"},
    {id:"TUN16",name:"Elias Saad",team:"Túnez"},
    {id:"TUN17",name:"Hazem Mastouri",team:"Túnez"},
    {id:"TUN18",name:"Ismael Gharbi",team:"Túnez"},
    {id:"TUN19",name:"Sayfallah Ltaief",team:"Túnez"},
    {id:"TUN20",name:"Naim Sliti",team:"Túnez"},
    // Belgium
    {id:"BEL1",name:"Team Logo",team:"Bélgica",type:"foil"},
    {id:"BEL2",name:"Thibaut Courtois",team:"Bélgica"},
    {id:"BEL3",name:"Arthur Theate",team:"Bélgica"},
    {id:"BEL4",name:"Timothy Castagne",team:"Bélgica"},
    {id:"BEL5",name:"Zeno Debast",team:"Bélgica"},
    {id:"BEL6",name:"Brandon Mechele",team:"Bélgica"},
    {id:"BEL7",name:"Maxim De Cuyper",team:"Bélgica"},
    {id:"BEL8",name:"Thomas Meunier",team:"Bélgica"},
    {id:"BEL9",name:"Youri Tielemans",team:"Bélgica"},
    {id:"BEL10",name:"Amadou Onana",team:"Bélgica"},
    {id:"BEL11",name:"Nicolas Raskin",team:"Bélgica"},
    {id:"BEL12",name:"Alexis Saelemaekers",team:"Bélgica"},
    {id:"BEL13",name:"Team Photo",team:"Bélgica"},
    {id:"BEL14",name:"Hans Vanaken",team:"Bélgica"},
    {id:"BEL15",name:"Kevin De Bruyne",team:"Bélgica"},
    {id:"BEL16",name:"Jérémy Doku",team:"Bélgica"},
    {id:"BEL17",name:"Charles De Ketelaere",team:"Bélgica"},
    {id:"BEL18",name:"Leandro Trossard",team:"Bélgica"},
    {id:"BEL19",name:"Loïs Openda",team:"Bélgica"},
    {id:"BEL20",name:"Romelu Lukaku",team:"Bélgica"},
    // Egypt
    {id:"EGY1",name:"Team Logo",team:"Egipto",type:"foil"},
    {id:"EGY2",name:"Mohamed El Shenawy",team:"Egipto"},
    {id:"EGY3",name:"Mohamed Hany",team:"Egipto"},
    {id:"EGY4",name:"Mohamed Hamdy",team:"Egipto"},
    {id:"EGY5",name:"Yasser Ibrahim",team:"Egipto"},
    {id:"EGY6",name:"Khaled Sobhi",team:"Egipto"},
    {id:"EGY7",name:"Ramy Rabia",team:"Egipto"},
    {id:"EGY8",name:"Hossam Abdelmaguid",team:"Egipto"},
    {id:"EGY9",name:"Ahmed Fatouh",team:"Egipto"},
    {id:"EGY10",name:"Marwan Attia",team:"Egipto"},
    {id:"EGY11",name:"Zizo",team:"Egipto"},
    {id:"EGY12",name:"Hamdy Fathy",team:"Egipto"},
    {id:"EGY13",name:"Team Photo",team:"Egipto"},
    {id:"EGY14",name:"Mohamed Lasheen",team:"Egipto"},
    {id:"EGY15",name:"Emam Ashour",team:"Egipto"},
    {id:"EGY16",name:"Osama Faisal",team:"Egipto"},
    {id:"EGY17",name:"Mohamed Salah",team:"Egipto"},
    {id:"EGY18",name:"Mostafa Mohamed",team:"Egipto"},
    {id:"EGY19",name:"Trezeguet",team:"Egipto"},
    {id:"EGY20",name:"Omar Marmoush",team:"Egipto"},
    // Iran
    {id:"IRN1",name:"Team Logo",team:"Irán",type:"foil"},
    {id:"IRN2",name:"Alireza Beiranvand",team:"Irán"},
    {id:"IRN3",name:"Morteza Pouraliganji",team:"Irán"},
    {id:"IRN4",name:"Ehsan Hajsafi",team:"Irán"},
    {id:"IRN5",name:"Milad Mohammadi",team:"Irán"},
    {id:"IRN6",name:"Shojae Khalilzadeh",team:"Irán"},
    {id:"IRN7",name:"Ramin Rezaeian",team:"Irán"},
    {id:"IRN8",name:"Hossein Kanaani",team:"Irán"},
    {id:"IRN9",name:"Sadegh Moharrami",team:"Irán"},
    {id:"IRN10",name:"Saleh Hardani",team:"Irán"},
    {id:"IRN11",name:"Saeed Ezatolahi",team:"Irán"},
    {id:"IRN12",name:"Saman Ghoddos",team:"Irán"},
    {id:"IRN13",name:"Team Photo",team:"Irán"},
    {id:"IRN14",name:"Omid Noorafkan",team:"Irán"},
    {id:"IRN15",name:"Roozbeh Cheshmi",team:"Irán"},
    {id:"IRN16",name:"Mohammad Mohebi",team:"Irán"},
    {id:"IRN17",name:"Sardar Azmoun",team:"Irán"},
    {id:"IRN18",name:"Mehdi Taremi",team:"Irán"},
    {id:"IRN19",name:"Alireza Jahanbakhsh",team:"Irán"},
    {id:"IRN20",name:"Ali Gholizadeh",team:"Irán"},
    // New Zealand
    {id:"NZL1",name:"Team Logo",team:"Nueva Zelanda",type:"foil"},
    {id:"NZL2",name:"Max Crocombe Payne",team:"Nueva Zelanda"},
    {id:"NZL3",name:"Alex Paulsen",team:"Nueva Zelanda"},
    {id:"NZL4",name:"Michael Boxall",team:"Nueva Zelanda"},
    {id:"NZL5",name:"Liberato Cacace",team:"Nueva Zelanda"},
    {id:"NZL6",name:"Tim Payne",team:"Nueva Zelanda"},
    {id:"NZL7",name:"Tyler Bindon",team:"Nueva Zelanda"},
    {id:"NZL8",name:"Francis de Vries",team:"Nueva Zelanda"},
    {id:"NZL9",name:"Finn Surman",team:"Nueva Zelanda"},
    {id:"NZL10",name:"Joe Bell",team:"Nueva Zelanda"},
    {id:"NZL11",name:"Sarpreet Singh",team:"Nueva Zelanda"},
    {id:"NZL12",name:"Ryan Thomas",team:"Nueva Zelanda"},
    {id:"NZL13",name:"Team Photo",team:"Nueva Zelanda"},
    {id:"NZL14",name:"Matthew Garbett",team:"Nueva Zelanda"},
    {id:"NZL15",name:"Marko Stamenić",team:"Nueva Zelanda"},
    {id:"NZL16",name:"Ben Old",team:"Nueva Zelanda"},
    {id:"NZL17",name:"Chris Wood",team:"Nueva Zelanda"},
    {id:"NZL18",name:"Elijah Just",team:"Nueva Zelanda"},
    {id:"NZL19",name:"Callum McCowatt",team:"Nueva Zelanda"},
    {id:"NZL20",name:"Kosta Barbarouses",team:"Nueva Zelanda"},
    // Spain
    {id:"ESP1",name:"Team Logo",team:"España",type:"foil"},
    {id:"ESP2",name:"Unai Simon",team:"España"},
    {id:"ESP3",name:"Robin Le Normand",team:"España"},
    {id:"ESP4",name:"Aymeric Laporte",team:"España"},
    {id:"ESP5",name:"Dean Huijsen",team:"España"},
    {id:"ESP6",name:"Pedro Porro",team:"España"},
    {id:"ESP7",name:"Dani Carvajal",team:"España"},
    {id:"ESP8",name:"Marc Cucurella",team:"España"},
    {id:"ESP9",name:"Martín Zubimendi",team:"España"},
    {id:"ESP10",name:"Rodri",team:"España"},
    {id:"ESP11",name:"Pedri",team:"España"},
    {id:"ESP12",name:"Fabian Ruiz",team:"España"},
    {id:"ESP13",name:"Team Photo",team:"España"},
    {id:"ESP14",name:"Mikel Merino",team:"España"},
    {id:"ESP15",name:"Lamine Yamal",team:"España"},
    {id:"ESP16",name:"Dani Olmo",team:"España"},
    {id:"ESP17",name:"Nico Williams",team:"España"},
    {id:"ESP18",name:"Ferran Torres",team:"España"},
    {id:"ESP19",name:"Álvaro Morata",team:"España"},
    {id:"ESP20",name:"Mikel Oyarzabal",team:"España"},
    // Cape Verde
    {id:"CPV1",name:"Team Logo",team:"Cabo Verde",type:"foil"},
    {id:"CPV2",name:"Vozinha",team:"Cabo Verde"},
    {id:"CPV3",name:"Logan Costa",team:"Cabo Verde"},
    {id:"CPV4",name:"Pico",team:"Cabo Verde"},
    {id:"CPV5",name:"Diney",team:"Cabo Verde"},
    {id:"CPV6",name:"Steven Moreira",team:"Cabo Verde"},
    {id:"CPV7",name:"Wagner Pina",team:"Cabo Verde"},
    {id:"CPV8",name:"Joao Paulo",team:"Cabo Verde"},
    {id:"CPV9",name:"Yannick Semedo",team:"Cabo Verde"},
    {id:"CPV10",name:"Kevin Pina",team:"Cabo Verde"},
    {id:"CPV11",name:"Patrick Andrade",team:"Cabo Verde"},
    {id:"CPV12",name:"Jamiro Monteiro",team:"Cabo Verde"},
    {id:"CPV13",name:"Team Photo",team:"Cabo Verde"},
    {id:"CPV14",name:"Deroy Duarte",team:"Cabo Verde"},
    {id:"CPV15",name:"Garry Rodrigues",team:"Cabo Verde"},
    {id:"CPV16",name:"Jovane Cabral",team:"Cabo Verde"},
    {id:"CPV17",name:"Ryan Mendes",team:"Cabo Verde"},
    {id:"CPV18",name:"Dailon Livramento",team:"Cabo Verde"},
    {id:"CPV19",name:"Willy Semedo",team:"Cabo Verde"},
    {id:"CPV20",name:"Bebe",team:"Cabo Verde"},
    // Saudi Arabia
    {id:"KSA1",name:"Team Logo",team:"Arabia Saudita",type:"foil"},
    {id:"KSA2",name:"Nawaf Alaqidi",team:"Arabia Saudita"},
    {id:"KSA3",name:"Abdulrahman Al-Sanbi",team:"Arabia Saudita"},
    {id:"KSA4",name:"Saud Abdulhamid",team:"Arabia Saudita"},
    {id:"KSA5",name:"Nawaf Bouwashl",team:"Arabia Saudita"},
    {id:"KSA6",name:"Jihad Thakri",team:"Arabia Saudita"},
    {id:"KSA7",name:"Moteb Al-Harbi",team:"Arabia Saudita"},
    {id:"KSA8",name:"Hassan Altambakti",team:"Arabia Saudita"},
    {id:"KSA9",name:"Musab Aljuwayr",team:"Arabia Saudita"},
    {id:"KSA10",name:"Ziyad Aljohani",team:"Arabia Saudita"},
    {id:"KSA11",name:"Abdullah Alkhaibari",team:"Arabia Saudita"},
    {id:"KSA12",name:"Nasser Aldawsari",team:"Arabia Saudita"},
    {id:"KSA13",name:"Team Photo",team:"Arabia Saudita"},
    {id:"KSA14",name:"Saleh Abu Alshamat",team:"Arabia Saudita"},
    {id:"KSA15",name:"Marwan Alsahafi",team:"Arabia Saudita"},
    {id:"KSA16",name:"Salem Aldawsari",team:"Arabia Saudita"},
    {id:"KSA17",name:"Abdulrahman Al-Aboud",team:"Arabia Saudita"},
    {id:"KSA18",name:"Feras Akbrikan",team:"Arabia Saudita"},
    {id:"KSA19",name:"Saleh Alshehri",team:"Arabia Saudita"},
    {id:"KSA20",name:"Abdullah Al-Hamdan",team:"Arabia Saudita"},
    // Uruguay
    {id:"URU1",name:"Team Logo",team:"Uruguay",type:"foil"},
    {id:"URU2",name:"Sergio Rochet",team:"Uruguay"},
    {id:"URU3",name:"Santiago Mele",team:"Uruguay"},
    {id:"URU4",name:"Ronald Araujo",team:"Uruguay"},
    {id:"URU5",name:"José María Giménez",team:"Uruguay"},
    {id:"URU6",name:"Sebastian Caceres",team:"Uruguay"},
    {id:"URU7",name:"Mathias Olivera",team:"Uruguay"},
    {id:"URU8",name:"Guillermo Varela",team:"Uruguay"},
    {id:"URU9",name:"Nahitan Nandez",team:"Uruguay"},
    {id:"URU10",name:"Federico Valverde",team:"Uruguay"},
    {id:"URU11",name:"Giorgian De Arrascaeta",team:"Uruguay"},
    {id:"URU12",name:"Rodrigo Bentancur",team:"Uruguay"},
    {id:"URU13",name:"Team Photo",team:"Uruguay"},
    {id:"URU14",name:"Manuel Ugarte",team:"Uruguay"},
    {id:"URU15",name:"Nicolás de la Cruz",team:"Uruguay"},
    {id:"URU16",name:"Maxi Araujo",team:"Uruguay"},
    {id:"URU17",name:"Darwin Núñez",team:"Uruguay"},
    {id:"URU18",name:"Federico Viñas",team:"Uruguay"},
    {id:"URU19",name:"Rodrigo Aguirre",team:"Uruguay"},
    {id:"URU20",name:"Facundo Pellistri",team:"Uruguay"},
    // France
    {id:"FRA1",name:"Team Logo",team:"Francia",type:"foil"},
    {id:"FRA2",name:"Mike Maignan",team:"Francia"},
    {id:"FRA3",name:"Theo Hernandez",team:"Francia"},
    {id:"FRA4",name:"William Saliba",team:"Francia"},
    {id:"FRA5",name:"Jules Kounde",team:"Francia"},
    {id:"FRA6",name:"Ibrahima Konate",team:"Francia"},
    {id:"FRA7",name:"Dayot Upamecano",team:"Francia"},
    {id:"FRA8",name:"Lucas Digne",team:"Francia"},
    {id:"FRA9",name:"Aurélien Tchouaméni",team:"Francia"},
    {id:"FRA10",name:"Eduardo Camavinga",team:"Francia"},
    {id:"FRA11",name:"Manu Kone",team:"Francia"},
    {id:"FRA12",name:"Adrien Rabiot",team:"Francia"},
    {id:"FRA13",name:"Team Photo",team:"Francia"},
    {id:"FRA14",name:"Michael Olise",team:"Francia"},
    {id:"FRA15",name:"Ousmane Dembele",team:"Francia"},
    {id:"FRA16",name:"Bradley Barcola",team:"Francia"},
    {id:"FRA17",name:"Désiré Doué",team:"Francia"},
    {id:"FRA18",name:"Kingsley Coman",team:"Francia"},
    {id:"FRA19",name:"Hugo Ekitike",team:"Francia"},
    {id:"FRA20",name:"Kylian Mbappe",team:"Francia"},
    // Senegal
    {id:"SEN1",name:"Team Logo",team:"Senegal",type:"foil"},
    {id:"SEN2",name:"Edouard Mendy",team:"Senegal"},
    {id:"SEN3",name:"Yehvann Diouf",team:"Senegal"},
    {id:"SEN4",name:"Moussa Niakhaté",team:"Senegal"},
    {id:"SEN5",name:"Abdoulaye Seck",team:"Senegal"},
    {id:"SEN6",name:"Ismail Jakobs",team:"Senegal"},
    {id:"SEN7",name:"El Hadji Malick Diouf",team:"Senegal"},
    {id:"SEN8",name:"Kalidou Koulibaly",team:"Senegal"},
    {id:"SEN9",name:"Idrissa Gana Gueye",team:"Senegal"},
    {id:"SEN10",name:"Pape Matar Sarr",team:"Senegal"},
    {id:"SEN11",name:"Pape Gueye",team:"Senegal"},
    {id:"SEN12",name:"Habib Diarra",team:"Senegal"},
    {id:"SEN13",name:"Team Photo",team:"Senegal"},
    {id:"SEN14",name:"Lamine Camara",team:"Senegal"},
    {id:"SEN15",name:"Sadio Mane",team:"Senegal"},
    {id:"SEN16",name:"Ismaïla Sarr",team:"Senegal"},
    {id:"SEN17",name:"Boulaye Dia",team:"Senegal"},
    {id:"SEN18",name:"Iliman Ndiaye",team:"Senegal"},
    {id:"SEN19",name:"Nicolas Jackson",team:"Senegal"},
    {id:"SEN20",name:"Krepin Diatta",team:"Senegal"},
    // Iraq
    {id:"IRQ1",name:"Team Logo",team:"Irak",type:"foil"},
    {id:"IRQ2",name:"Jalal Hassan",team:"Irak"},
    {id:"IRQ3",name:"Rebin Sulaka",team:"Irak"},
    {id:"IRQ4",name:"Hussein Ali",team:"Irak"},
    {id:"IRQ5",name:"Akam Hashem",team:"Irak"},
    {id:"IRQ6",name:"Merchas Doski",team:"Irak"},
    {id:"IRQ7",name:"Zaid Tahseen",team:"Irak"},
    {id:"IRQ8",name:"Manaf Younis",team:"Irak"},
    {id:"IRQ9",name:"Zidane Iqbal",team:"Irak"},
    {id:"IRQ10",name:"Amir Al-Ammari",team:"Irak"},
    {id:"IRQ11",name:"Ibrahim Bavesh",team:"Irak"},
    {id:"IRQ12",name:"Ali Jasim",team:"Irak"},
    {id:"IRQ13",name:"Team Photo",team:"Irak"},
    {id:"IRQ14",name:"Youssef Amyn",team:"Irak"},
    {id:"IRQ15",name:"Aimar Sher",team:"Irak"},
    {id:"IRQ16",name:"Marko Farji",team:"Irak"},
    {id:"IRQ17",name:"Osama Rashid",team:"Irak"},
    {id:"IRQ18",name:"Ali Al-Hamadi",team:"Irak"},
    {id:"IRQ19",name:"Aymen Hussein",team:"Irak"},
    {id:"IRQ20",name:"Mohanad Ali",team:"Irak"},
    // Norway
    {id:"NOR1",name:"Team Logo",team:"Noruega",type:"foil"},
    {id:"NOR2",name:"Orjan Nyland",team:"Noruega"},
    {id:"NOR3",name:"Julian Ryerson",team:"Noruega"},
    {id:"NOR4",name:"Leo Ostigård",team:"Noruega"},
    {id:"NOR5",name:"Kristoffer Vassbakk Ajer",team:"Noruega"},
    {id:"NOR6",name:"Marcus Holmgren Pedersen",team:"Noruega"},
    {id:"NOR7",name:"David Møller Wolfe",team:"Noruega"},
    {id:"NOR8",name:"Torbjørn Heggem",team:"Noruega"},
    {id:"NOR9",name:"Morten Thorsby",team:"Noruega"},
    {id:"NOR10",name:"Martin Ødegaard",team:"Noruega"},
    {id:"NOR11",name:"Sander Berge",team:"Noruega"},
    {id:"NOR12",name:"Andreas Schjelderup",team:"Noruega"},
    {id:"NOR13",name:"Team Photo",team:"Noruega"},
    {id:"NOR14",name:"Patrick Berg",team:"Noruega"},
    {id:"NOR15",name:"Erling Haaland",team:"Noruega"},
    {id:"NOR16",name:"Alexander Sørloth",team:"Noruega"},
    {id:"NOR17",name:"Aron Dønnum",team:"Noruega"},
    {id:"NOR18",name:"Jorgen Strand Larsen",team:"Noruega"},
    {id:"NOR19",name:"Antonio Nusa",team:"Noruega"},
    {id:"NOR20",name:"Oscar Bobb",team:"Noruega"},
    // Argentina
    {id:"ARG1",name:"Team Logo",team:"Argentina",type:"foil"},
    {id:"ARG2",name:"Emiliano Martinez",team:"Argentina"},
    {id:"ARG3",name:"Nahuel Molina",team:"Argentina"},
    {id:"ARG4",name:"Cristian Romero",team:"Argentina"},
    {id:"ARG5",name:"Nicolas Otamendi",team:"Argentina"},
    {id:"ARG6",name:"Nicolas Tagliafico",team:"Argentina"},
    {id:"ARG7",name:"Leonardo Balerdi",team:"Argentina"},
    {id:"ARG8",name:"Enzo Fernandez",team:"Argentina"},
    {id:"ARG9",name:"Alexis Mac Allister",team:"Argentina"},
    {id:"ARG10",name:"Rodrigo De Paul",team:"Argentina"},
    {id:"ARG11",name:"Exequiel Palacios",team:"Argentina"},
    {id:"ARG12",name:"Leandro Paredes",team:"Argentina"},
    {id:"ARG13",name:"Team Photo",team:"Argentina"},
    {id:"ARG14",name:"Nico Paz",team:"Argentina"},
    {id:"ARG15",name:"Franco Mastantuono",team:"Argentina"},
    {id:"ARG16",name:"Nico Gonzalez",team:"Argentina"},
    {id:"ARG17",name:"Lionel Messi",team:"Argentina"},
    {id:"ARG18",name:"Lautaro Martinez",team:"Argentina"},
    {id:"ARG19",name:"Julian Alvarez",team:"Argentina"},
    {id:"ARG20",name:"Giuliano Simeone",team:"Argentina"},
    // Algeria
    {id:"ALG1",name:"Team Logo",team:"Argelia",type:"foil"},
    {id:"ALG2",name:"Alexis Guendouz",team:"Argelia"},
    {id:"ALG3",name:"Ramy Bensebaini",team:"Argelia"},
    {id:"ALG4",name:"Youcef Atal",team:"Argelia"},
    {id:"ALG5",name:"Rayan Aït-Nouri",team:"Argelia"},
    {id:"ALG6",name:"Mohamed Amine Tougai",team:"Argelia"},
    {id:"ALG7",name:"Aïssa Mandi",team:"Argelia"},
    {id:"ALG8",name:"Ismael Bennacer",team:"Argelia"},
    {id:"ALG9",name:"Houssem Aquar",team:"Argelia"},
    {id:"ALG10",name:"Hicham Boudaoui",team:"Argelia"},
    {id:"ALG11",name:"Ramiz Zerrouki",team:"Argelia"},
    {id:"ALG12",name:"Nabil Bentalab",team:"Argelia"},
    {id:"ALG13",name:"Team Photo",team:"Argelia"},
    {id:"ALG14",name:"Farés Chaibi",team:"Argelia"},
    {id:"ALG15",name:"Riyad Mahrez",team:"Argelia"},
    {id:"ALG16",name:"Said Benrahma",team:"Argelia"},
    {id:"ALG17",name:"Anis Hadj Moussa",team:"Argelia"},
    {id:"ALG18",name:"Amine Gouiri",team:"Argelia"},
    {id:"ALG19",name:"Baghdad Bounedjah",team:"Argelia"},
    {id:"ALG20",name:"Mohammed Amoura",team:"Argelia"},
    // Austria
    {id:"AUT1",name:"Team Logo",team:"Austria",type:"foil"},
    {id:"AUT2",name:"Alexander Schlager",team:"Austria"},
    {id:"AUT3",name:"Patrick Pentz",team:"Austria"},
    {id:"AUT4",name:"David Alaba",team:"Austria"},
    {id:"AUT5",name:"Kevin Danso",team:"Austria"},
    {id:"AUT6",name:"Philipp Lienhart",team:"Austria"},
    {id:"AUT7",name:"Stefan Posch",team:"Austria"},
    {id:"AUT8",name:"Phillipp Mwene",team:"Austria"},
    {id:"AUT9",name:"Alexander Prass",team:"Austria"},
    {id:"AUT10",name:"Xaver Schlager",team:"Austria"},
    {id:"AUT11",name:"Marcel Sabitzer",team:"Austria"},
    {id:"AUT12",name:"Konrad Laimer",team:"Austria"},
    {id:"AUT13",name:"Team Photo",team:"Austria"},
    {id:"AUT14",name:"Florian Grillitsch",team:"Austria"},
    {id:"AUT15",name:"Nicolas Seiwald",team:"Austria"},
    {id:"AUT16",name:"Romano Schmid",team:"Austria"},
    {id:"AUT17",name:"Patrick Wimmer",team:"Austria"},
    {id:"AUT18",name:"Christoph Baumgartner",team:"Austria"},
    {id:"AUT19",name:"Michael Gregoritsch",team:"Austria"},
    {id:"AUT20",name:"Marko Arnautović",team:"Austria"},
    // Jordan
    {id:"JOR1",name:"Team Logo",team:"Jordania",type:"foil"},
    {id:"JOR2",name:"Yazeed Abulaila",team:"Jordania"},
    {id:"JOR3",name:"Ihsan Haddad",team:"Jordania"},
    {id:"JOR4",name:"Mohammad Abu Hashish",team:"Jordania"},
    {id:"JOR5",name:"Yazan Al-Arab",team:"Jordania"},
    {id:"JOR6",name:"Abdallah Nasib",team:"Jordania"},
    {id:"JOR7",name:"Saleem Obaid",team:"Jordania"},
    {id:"JOR8",name:"Mohammad Abualnadi",team:"Jordania"},
    {id:"JOR9",name:"Ibrahim Saadeh",team:"Jordania"},
    {id:"JOR10",name:"Nizar Al-Rashdan",team:"Jordania"},
    {id:"JOR11",name:"Noor Al-Rawabdeh",team:"Jordania"},
    {id:"JOR12",name:"Mohannad Abu Taha",team:"Jordania"},
    {id:"JOR13",name:"Team Photo",team:"Jordania"},
    {id:"JOR14",name:"Amer Jamous",team:"Jordania"},
    {id:"JOR15",name:"Musa Al-Taamari",team:"Jordania"},
    {id:"JOR16",name:"Yazan Al-Naimat",team:"Jordania"},
    {id:"JOR17",name:"Mahmoud Al-Mardi",team:"Jordania"},
    {id:"JOR18",name:"Ali Olwan",team:"Jordania"},
    {id:"JOR19",name:"Mohammad Abu Zrayq",team:"Jordania"},
    {id:"JOR20",name:"Ibrahim Sabra",team:"Jordania"},
    // Portugal
    {id:"POR1",name:"Team Logo",team:"Portugal",type:"foil"},
    {id:"POR2",name:"Diogo Costa",team:"Portugal"},
    {id:"POR3",name:"Jose Sa",team:"Portugal"},
    {id:"POR4",name:"Ruben Dias",team:"Portugal"},
    {id:"POR5",name:"João Cancelo",team:"Portugal"},
    {id:"POR6",name:"Diogo Dalot",team:"Portugal"},
    {id:"POR7",name:"Nuno Mendes",team:"Portugal"},
    {id:"POR8",name:"Gonçalo Inácio",team:"Portugal"},
    {id:"POR9",name:"Vitinha",team:"Portugal"},
    {id:"POR10",name:"Joao Palhinha",team:"Portugal"},
    {id:"POR11",name:"Bernardo Silva",team:"Portugal"},
    {id:"POR12",name:"Bruno Fernandes",team:"Portugal"},
    {id:"POR13",name:"Team Photo",team:"Portugal"},
    {id:"POR14",name:"Pedro Neto",team:"Portugal"},
    {id:"POR15",name:"Rafael Leao",team:"Portugal"},
    {id:"POR16",name:"Joao Felix",team:"Portugal"},
    {id:"POR17",name:"Cristiano Ronaldo",team:"Portugal"},
    {id:"POR18",name:"Gonçalo Ramos",team:"Portugal"},
    {id:"POR19",name:"Francisco Conceição",team:"Portugal"},
    {id:"POR20",name:"Pedro Gonçalves",team:"Portugal"},
    // Colombia
    {id:"COL1",name:"Team Logo",team:"Colombia",type:"foil"},
    {id:"COL2",name:"Camilo Vargas",team:"Colombia"},
    {id:"COL3",name:"Santiago Arias",team:"Colombia"},
    {id:"COL4",name:"Jhon Lucumí",team:"Colombia"},
    {id:"COL5",name:"Davinson Sánchez",team:"Colombia"},
    {id:"COL6",name:"Daniel Muñoz",team:"Colombia"},
    {id:"COL7",name:"Johan Mojica",team:"Colombia"},
    {id:"COL8",name:"Wilmar Barrios",team:"Colombia"},
    {id:"COL9",name:"Gustavo Puerta",team:"Colombia"},
    {id:"COL10",name:"Richard Ríos",team:"Colombia"},
    {id:"COL11",name:"Juan Cuadrado",team:"Colombia"},
    {id:"COL12",name:"Mateus Uribe",team:"Colombia"},
    {id:"COL13",name:"Team Photo",team:"Colombia"},
    {id:"COL14",name:"Jorge Carrascal",team:"Colombia"},
    {id:"COL15",name:"James Rodríguez",team:"Colombia"},
    {id:"COL16",name:"Luis Díaz",team:"Colombia"},
    {id:"COL17",name:"Rafael Santos Borré",team:"Colombia"},
    {id:"COL18",name:"Jhon Córdoba",team:"Colombia"},
    {id:"COL19",name:"Jhon Jáder Durán",team:"Colombia"},
    {id:"COL20",name:"Falcao",team:"Colombia"},
    // Croatia
    {id:"CRO1",name:"Team Logo",team:"Croacia",type:"foil"},
    {id:"CRO2",name:"Dominik Livaković",team:"Croacia"},
    {id:"CRO3",name:"Josip Šutalo",team:"Croacia"},
    {id:"CRO4",name:"Duje Ćaleta-Car",team:"Croacia"},
    {id:"CRO5",name:"Josip Stanišić",team:"Croacia"},
    {id:"CRO6",name:"Borna Sosa",team:"Croacia"},
    {id:"CRO7",name:"Martin Erlić",team:"Croacia"},
    {id:"CRO8",name:"Tin Jedvaj",team:"Croacia"},
    {id:"CRO9",name:"Luka Modrić",team:"Croacia"},
    {id:"CRO10",name:"Mateo Kovačić",team:"Croacia"},
    {id:"CRO11",name:"Marcelo Brozović",team:"Croacia"},
    {id:"CRO12",name:"Mario Pašalić",team:"Croacia"},
    {id:"CRO13",name:"Team Photo",team:"Croacia"},
    {id:"CRO14",name:"Lovro Majer",team:"Croacia"},
    {id:"CRO15",name:"Luka Sučić",team:"Croacia"},
    {id:"CRO16",name:"Ante Budimir",team:"Croacia"},
    {id:"CRO17",name:"Ivan Perišić",team:"Croacia"},
    {id:"CRO18",name:"Marko Pjaca",team:"Croacia"},
    {id:"CRO19",name:"Andrej Kramarić",team:"Croacia"},
    {id:"CRO20",name:"Bruno Petković",team:"Croacia"},
    // Ghana
    {id:"GHA1",name:"Team Logo",team:"Ghana",type:"foil"},
    {id:"GHA2",name:"Lawrence Ati-Zigi",team:"Ghana"},
    {id:"GHA3",name:"Abdul Manaf Nurudeen",team:"Ghana"},
    {id:"GHA4",name:"Daniel Amartey",team:"Ghana"},
    {id:"GHA5",name:"Denis Odoi",team:"Ghana"},
    {id:"GHA6",name:"Alexander Djiku",team:"Ghana"},
    {id:"GHA7",name:"Gideon Mensah",team:"Ghana"},
    {id:"GHA8",name:"Baba Rahman",team:"Ghana"},
    {id:"GHA9",name:"Elisha Owusu",team:"Ghana"},
    {id:"GHA10",name:"Thomas Partey",team:"Ghana"},
    {id:"GHA11",name:"Salis Abdul Samed",team:"Ghana"},
    {id:"GHA12",name:"Kudus Mohammed",team:"Ghana"},
    {id:"GHA13",name:"Team Photo",team:"Ghana"},
    {id:"GHA14",name:"Antoine Semenyo",team:"Ghana"},
    {id:"GHA15",name:"Jordan Ayew",team:"Ghana"},
    {id:"GHA16",name:"Inaki Williams",team:"Ghana"},
    {id:"GHA17",name:"Osman Bukari",team:"Ghana"},
    {id:"GHA18",name:"Felix Afena-Gyan",team:"Ghana"},
    {id:"GHA19",name:"Daniel Afriyie Barnieh",team:"Ghana"},
    {id:"GHA20",name:"Ernest Nuamah",team:"Ghana"},
    // England
    {id:"ENG1",name:"Team Logo",team:"Inglaterra",type:"foil"},
    {id:"ENG2",name:"Jordan Pickford",team:"Inglaterra"},
    {id:"ENG3",name:"Dean Henderson",team:"Inglaterra"},
    {id:"ENG4",name:"John Stones",team:"Inglaterra"},
    {id:"ENG5",name:"Marc Guehi",team:"Inglaterra"},
    {id:"ENG6",name:"Trent Alexander-Arnold",team:"Inglaterra"},
    {id:"ENG7",name:"Kyle Walker",team:"Inglaterra"},
    {id:"ENG8",name:"Luke Shaw",team:"Inglaterra"},
    {id:"ENG9",name:"Declan Rice",team:"Inglaterra"},
    {id:"ENG10",name:"Conor Gallagher",team:"Inglaterra"},
    {id:"ENG11",name:"Jude Bellingham",team:"Inglaterra"},
    {id:"ENG12",name:"Phil Foden",team:"Inglaterra"},
    {id:"ENG13",name:"Team Photo",team:"Inglaterra"},
    {id:"ENG14",name:"Kobbie Mainoo",team:"Inglaterra"},
    {id:"ENG15",name:"Bukayo Saka",team:"Inglaterra"},
    {id:"ENG16",name:"Marcus Rashford",team:"Inglaterra"},
    {id:"ENG17",name:"Harry Kane",team:"Inglaterra"},
    {id:"ENG18",name:"Ollie Watkins",team:"Inglaterra"},
    {id:"ENG19",name:"Cole Palmer",team:"Inglaterra"},
    {id:"ENG20",name:"Anthony Gordon",team:"Inglaterra"},

    // Panama
    {id:"PAN1",name:"Team Logo",team:"Panamá",type:"foil"},
    {id:"PAN2",name:"Luis Mejía",team:"Panamá"},
    {id:"PAN3",name:"Harold Cummings",team:"Panamá"},
    {id:"PAN4",name:"Fidel Escobar",team:"Panamá"},
    {id:"PAN5",name:"Eric Davis",team:"Panamá"},
    {id:"PAN6",name:"Azmahar Ariano",team:"Panamá"},
    {id:"PAN7",name:"Michael Murillo",team:"Panamá"},
    {id:"PAN8",name:"Alberto Quintero",team:"Panamá"},
    {id:"PAN9",name:"Edgar Bárcenas",team:"Panamá"},
    {id:"PAN10",name:"Adalberto Carrasquilla",team:"Panamá"},
    {id:"PAN11",name:"Anibal Godoy",team:"Panamá"},
    {id:"PAN12",name:"José Fajardo",team:"Panamá"},
    {id:"PAN13",name:"Team Photo",team:"Panamá"},
    {id:"PAN14",name:"Ismael Díaz",team:"Panamá"},
    {id:"PAN15",name:"Rolando Blackburn",team:"Panamá"},
    {id:"PAN16",name:"Freddy Góndola",team:"Panamá"},
    {id:"PAN17",name:"Cecilio Waterman",team:"Panamá"},
    {id:"PAN18",name:"Iván Anderson",team:"Panamá"},
    {id:"PAN19",name:"César Blackman",team:"Panamá"},
    {id:"PAN20",name:"Blas Pérez",team:"Panamá"},

    // Congo DR
    {id:"COD1",name:"Team Logo",team:"Congo DR",type:"foil"},
    {id:"COD2",name:"LIONEL MPASI",team:"Congo DR"},
    {id:"COD3",name:"AARON WAN-BISSAKA",team:"Congo DR"},
    {id:"COD4",name:"AXEL TUANZEBE",team:"Congo DR"},
    {id:"COD5",name:"ARTHUR MASUAKU",team:"Congo DR"},
    {id:"COD6",name:"CHANCEL MBEMBA",team:"Congo DR"},
    {id:"COD7",name:"JORIS KAVEMBE",team:"Congo DR"},
    {id:"COD8",name:"CHARLES PICKEL",team:"Congo DR"},
    {id:"COD9",name:"NGALAYEL MUKAU",team:"Congo DR"},
    {id:"COD10",name:"EDO KAVEMBE",team:"Congo DR"},
    {id:"COD11",name:"SAMUEL MOUTOUSSAMY",team:"Congo DR"},
    {id:"COD12",name:"NOAH SADIKI",team:"Congo DR"},
    {id:"COD13",name:"Team Photo",team:"Congo DR"},
    {id:"COD14",name:"THEO BONGONDA",team:"Congo DR"},
    {id:"COD15",name:"MESCHACK ELIA",team:"Congo DR"},
    {id:"COD16",name:"YOANE WISSA",team:"Congo DR"},
    {id:"COD17",name:"BRIAN CIPENGA",team:"Congo DR"},
    {id:"COD18",name:"FISTON MAYELE",team:"Congo DR"},
    {id:"COD19",name:"CEDRIC BAKAMBU",team:"Congo DR"},
    {id:"COD20",name:"NATHANAEL MBUKU",team:"Congo DR"},

    // Uzbekistan
    {id:"UZB1",name:"Team Logo",team:"Uzbekistán",type:"foil"},
    {id:"UZB2",name:"UTKIR VUSUPOV",team:"Uzbekistán"},
    {id:"UZB3",name:"FARRUKH SAYFIEV",team:"Uzbekistán"},
    {id:"UZB4",name:"SHERZOD NASRULLAEV",team:"Uzbekistán"},
    {id:"UZB5",name:"UMAR ESHMURODOV",team:"Uzbekistán"},
    {id:"UZB6",name:"HUSSNIDDIN ALIQULLOV",team:"Uzbekistán"},
    {id:"UZB7",name:"RUSTAM ASHURMATOV",team:"Uzbekistán"},
    {id:"UZB8",name:"KHOJIAKBAR ALIJONOV",team:"Uzbekistán"},
    {id:"UZB9",name:"ABDUKODIR KHUSANOV",team:"Uzbekistán"},
    {id:"UZB10",name:"ODILJON HAMROBEKOV",team:"Uzbekistán"},
    {id:"UZB11",name:"OTABEK SHUKUROV",team:"Uzbekistán"},
    {id:"UZB12",name:"JAMSHID ISKANDEROV",team:"Uzbekistán"},
    {id:"UZB13",name:"Team Photo",team:"Uzbekistán"},
    {id:"UZB14",name:"AZIZBEK TURGUNBOEV",team:"Uzbekistán"},
    {id:"UZB15",name:"KHOJIMAT ERKINOV",team:"Uzbekistán"},
    {id:"UZB16",name:"ELDOR SHOMURODOV",team:"Uzbekistán"},
    {id:"UZB17",name:"OSTON URUMOV",team:"Uzbekistán"},
    {id:"UZB18",name:"JALOLIDDIN MASHARIPOV",team:"Uzbekistán"},
    {id:"UZB19",name:"IGOR SERGEEV",team:"Uzbekistán"},
    {id:"UZB20",name:"ABBOSBEK FAYZULLAEV",team:"Uzbekistán"},
    ];


// Lista de equipos únicos — se genera automáticamente, no tocar
const TEAMS = [...new Map(
  STICKERS.map(s => [s.team, { name: s.team, flag: s.flag || "🏳️" }])
).values()];